---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by warfacez.
--- DateTime: 28.10.20 1:49
---

Maps.ZONE_ARGUS_KROKUUN = 830
Maps.ZONE_ARGUS_MACAREE = 882
Maps.ZONE_ARGUS_ANTORAN_WASTES = 885

addLocation(Maps.CONTINENT_ARGUS, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_CONTINENT, "Argus", {})

-- Zones
addLocation(Maps.ZONE_ARGUS_KROKUUN, Maps.CONTINENT_ARGUS, Maps.TYPE_ZONE, "Krokuun", {})
addLocation(Maps.ZONE_ARGUS_MACAREE, Maps.CONTINENT_ARGUS, Maps.TYPE_ZONE, "Mac'Aree", {})
addLocation(Maps.ZONE_ARGUS_ANTORAN_WASTES, Maps.CONTINENT_ARGUS, Maps.TYPE_ZONE, "Antoran Wastes", {})


-- Orphans
addLocation(903, Maps.ZONE_ARGUS_MACAREE, Maps.TYPE_ORPHAN, "The Seat of the Triumvirate", {})
addLocation(921, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Invasion Point: Aurinor", {})
addLocation(922, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Invasion Point: Bonich", {})
addLocation(923, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Invasion Point: Cen'gar", {})
addLocation(924, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Invasion Point: Naigtal", {})
addLocation(925, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Invasion Point: Sangua", {})
addLocation(926, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Invasion Point: Val", {})
addLocation(927, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Greater Invasion Point: Pit Lord Vilemus", {})
addLocation(928, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Greater Invasion Point: Mistress Alluradel", {})
addLocation(929, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Greater Invasion Point: Matron Folnuna", {})
addLocation(930, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Greater Invasion Point: Inquisitor Meto", {})
addLocation(931, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Greater Invasion Point: Sotanathor", {})
addLocation(932, Maps.CONTINENT_ARGUS, Maps.TYPE_ORPHAN, "Greater Invasion Point: Occularus", {})

-- Krokuun
addLocation(831, Maps.ZONE_ARGUS_KROKUUN, Maps.TYPE_MICRO, "The Vindicaar - Upper Deck", {})
addLocation(832, Maps.ZONE_ARGUS_KROKUUN, Maps.TYPE_MICRO, "The Vindicaar - Lower Deck", {})
addLocation(833, Maps.ZONE_ARGUS_KROKUUN, Maps.TYPE_MICRO, "Nath'raxas Spire", {})
addLocation(940, Maps.ZONE_ARGUS_KROKUUN, Maps.TYPE_DUNGEON, "The Vindicaar - Upper Deck", {})
addLocation(941, Maps.ZONE_ARGUS_KROKUUN, Maps.TYPE_DUNGEON, "The Vindicaar - Lower Deck", {})

-- Mac'Aree
addLocation(883, Maps.ZONE_ARGUS_MACAREE, Maps.TYPE_MICRO, "The Vindicaar - Upper Deck - Mac'Aree", {})
addLocation(884, Maps.ZONE_ARGUS_MACAREE, Maps.TYPE_MICRO, "The Vindicaar - Lower Deck - Mac'Aree", {})


-- Antoran Wastes
addLocation(886, Maps.ZONE_ARGUS_ANTORAN_WASTES, Maps.TYPE_MICRO, "The Vindicaar - Upper Deck", {})
addLocation(887, Maps.ZONE_ARGUS_ANTORAN_WASTES, Maps.TYPE_MICRO, "The Vindicaar - Lower Deck", {})

addLocation(909, Maps.ZONE_ARGUS_ANTORAN_WASTES, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Antorus, the Burning Throne", {})
addLocation(910, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Gaze of the Legion", {})
addLocation(911, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Halls of the Boundless Reach", {})
addLocation(912, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Elunaria", {})
addLocation(913, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Elarian Sanctuary", {})
addLocation(914, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - The Exhaust", {})
addLocation(915, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - The Burning Throne", {})
addLocation(916, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Chamber of Anguish", {})
addLocation(917, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - The World Soul", {})
addLocation(918, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Seat of the Pantheon", {})
addLocation(919, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Upper Deck", {})
addLocation(920, 909, Maps.TYPE_DUNGEON, "Antorus, the Burning Throne - Lower Deck", {})