---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by warfacez.
--- DateTime: 27.10.20 22:29
---

Maps.ZONE_BROKEN_ISLES_AZSUNA = 630
Maps.ZONE_BROKEN_ISLES_STORMHEIM = 634
Maps.ZONE_BROKEN_ISLES_VALSHARAH = 641
Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE = 646
Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN = 650
Maps.ZONE_BROKEN_ISLES_SURAMAR = 680
Maps.ZONE_BROKEN_ISLES_TRUESHOT_LODGE = 739
Maps.ZONE_BROKEN_ISLES_EYE_OF_AZSHARA = 790

addLocation(Maps.CONTINENT_BROKEN_ISLES, Maps.WORLD_AZEROTH, Maps.TYPE_CONTINENT, "Broken Isles", {})


-- Zones
addLocation(Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ZONE, "Azsuna", {})
addLocation(Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ZONE, "Stormheim", {})
addLocation(Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ZONE, "Val'sharah", {})
addLocation(Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ZONE, "Broken Shore", {})
addLocation(Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ZONE, "Highmountain", {})
addLocation(Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ZONE, "Suramar", {})
addLocation(Maps.ZONE_BROKEN_ISLES_TRUESHOT_LODGE, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_ZONE, "Trueshot Lodge", {})
addLocation(Maps.ZONE_BROKEN_ISLES_EYE_OF_AZSHARA, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ZONE, "Eye of Azshara", {})


-- Orphans
addLocation(645, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Twisting Nether", {})
addLocation(649, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_ORPHAN, "Helheim", {})
addLocation(676, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Broken Shore", {})
addLocation(877, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_ORPHAN, "Fields of the Eternal Hunt", {})
addLocation(671, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "The Cove of Nashal", {})

addLocation(672, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Mardum, the Shattered Abyss", {})
addLocation(673, 672, Maps.TYPE_MICRO, "Cryptic Hollow - Mardum, the Shattered Abyss", {})
addLocation(674, 672, Maps.TYPE_MICRO, "Soul Engine - Lower Soul Engine - Mardum, the Shattered Abyss", {})
addLocation(675, 672, Maps.TYPE_MICRO, "Soul Engine - Upper Soul Engine - Mardum, the Shattered Abyss", {})
addLocation(861, 672, Maps.TYPE_ORPHAN, "Mardum, the Shattered Abyss", {})
addLocation(879, 672, Maps.TYPE_DUNGEON, "Mardum, the Shattered Abyss - Upper Command Center", {})
addLocation(880, 672, Maps.TYPE_DUNGEON, "Mardum, the Shattered Abyss - Lower Command Center", {})

addLocation(694, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Helmouth Shallows", {})
addLocation(696, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Stormheim", {})
addLocation(709, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "The Wandering Isle", {})
addLocation(713, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_ORPHAN, "Eye of Azshara", {})
addLocation(714, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Niskara", {})
addLocation(717, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Dreadscar Rift", {})
addLocation(718, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Dreadscar Rift", {})
addLocation(731, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_ORPHAN, "Neltharion's Lair", {})
addLocation(733, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_ORPHAN, "Darkheart Thicket", {})

addLocation(747, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_ORPHAN, "The Dreamgrove", {})
addLocation(715, 747, Maps.TYPE_ORPHAN, "Emerald Dreamway", {})

addLocation(748, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Niskara", {})
addLocation(750, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_ORPHAN, "Thunder Totem", {})
addLocation(758, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_ORPHAN, "Gloaming Reef", {})
addLocation(793, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_ORPHAN, "Black Rook Hold", {})
addLocation(858, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Assault on Broken Shore", {})

addLocation(971, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Telogrus Rift", {})
addLocation(972, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "Telogrus Rift", {})
addLocation(726, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_ORPHAN, "The Maelstrom ", {})


-- Azsuna
addLocation(631, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_MICRO, "Nar'thalas Academy", {})
addLocation(632, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_MICRO, "Oceanus Cove", {})
addLocation(633, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_MICRO, "Temple of a Thousand Lights", {})

addLocation(677, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_DUNGEON, "Vault of the Wardens - Illidari Ward", {})
addLocation(678, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_DUNGEON, "Vault of the Wardens - Vault of the Wardens", {})
addLocation(679, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_DUNGEON, "Vault of the Wardens - The Warden's Court", {})
addLocation(710, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_DUNGEON, "Vault of the Wardens - The Warden's Court", {})
addLocation(711, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_DUNGEON, "Vault of the Wardens - Vault of the Wardens", {})
addLocation(712, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_DUNGEON, "Vault of the Wardens - Vault of the Betrayer", {})

addLocation(867, Maps.ZONE_BROKEN_ISLES_AZSUNA, Maps.TYPE_DUNGEON, "Azsuna", {})


-- Stormheim
addLocation(635, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_MICRO, "Shield's Rest", {})
addLocation(636, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_MICRO, "Stormscale Cavern", {})
addLocation(637, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_MICRO, "Thorignir Refuge - Floor 1", {})
addLocation(638, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_MICRO, "Thorignir Refuge - Floor 2", {})
addLocation(639, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_MICRO, "Aggramar's Vault", {})
addLocation(640, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_MICRO, "Vault of Eyir", {})

addLocation(703, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_DUNGEON, "Halls of Valor - Halls of Valor", {})
addLocation(704, 703, Maps.TYPE_DUNGEON, "Halls of Valor - The High Gate", {})
addLocation(705, 703, Maps.TYPE_DUNGEON, "Halls of Valor - Halls of Valor", {})

addLocation(706, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_DUNGEON, "Helmouth Cliffs - Helmouth Cliffs", {})
addLocation(707, 706, Maps.TYPE_DUNGEON, "Helmouth Cliffs - The Hold", {})
addLocation(708, 706, Maps.TYPE_DUNGEON, "Helmouth Cliffs - The Naglfar", {})

addLocation(806, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_DUNGEON, "Trial of Valor - Trial of Valor", {})
addLocation(807, 806, Maps.TYPE_DUNGEON, "Trial of Valor - Trial of Valor", {})
addLocation(808, 806, Maps.TYPE_DUNGEON, "Trial of Valor - Helheim", {})

addLocation(829, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_DUNGEON, "Halls of Valor", {})

addLocation(865, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_DUNGEON, "Stormheim - Floor 1", {})
addLocation(866, Maps.ZONE_BROKEN_ISLES_STORMHEIM, Maps.TYPE_DUNGEON, "Stormheim - Floor 2 ", {})


-- Val'sharah
addLocation(642, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_MICRO, "Darkpens", {})
addLocation(643, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_MICRO, "Sleeper's Barrow - Lower Sleepers Barrow", {})
addLocation(644, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_MICRO, "Sleeper's Barrow - Upper Sleepers Barrow", {})

addLocation(751, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "Black Rook Hold - The Ravenscrypt", {})
addLocation(752, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "Black Rook Hold - The Grand Hall", {})
addLocation(753, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "Black Rook Hold - Ravenshold", {})
addLocation(754, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "Black Rook Hold - The Rook's Roost", {})
addLocation(755, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "Black Rook Hold - Lord Ravencrest's Chamber", {})
addLocation(756, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "Black Rook Hold - The Raven's Crown", {})

addLocation(777, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - Clutch of Corruption", {})
addLocation(778, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - Core of the Nightmare", {})
addLocation(779, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - Mulgore", {})
addLocation(780, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - Un'goro Crater", {})
addLocation(781, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - The Emerald Nightmare", {})
addLocation(786, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - Grizzly Hills", {})
addLocation(787, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - Moonglade", {})
addLocation(788, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - Rift of Aln", {})
addLocation(789, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "The Emerald Nightmare - The Emerald Dream", {})

addLocation(868, Maps.ZONE_BROKEN_ISLES_VALSHARAH, Maps.TYPE_DUNGEON, "Val'sharah", {})


-- Broken Shore
addLocation(845, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Cathedral of Eternal Night - Hall of the Moon", {})
addLocation(846, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Cathedral of Eternal Night - Twilight Grove", {})
addLocation(847, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Cathedral of Eternal Night - The Emerald Archives", {})
addLocation(848, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Cathedral of Eternal Night - Path of Illumination", {})
addLocation(849, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Cathedral of Eternal Night - Sacristy of Elune", {})
addLocation(850, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Tomb of Sargeras - Chamber of the Moon", {})
addLocation(851, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Tomb of Sargeras - The Abyssal Throne", {})
addLocation(852, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Tomb of Sargeras - Terrace of the Moon", {})
addLocation(853, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Tomb of Sargeras - The Guardian's Sanctum", {})
addLocation(854, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Tomb of Sargeras - Chamber of the Avatar", {})
addLocation(855, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Tomb of Sargeras - Felstorm's Breach", {})
addLocation(856, Maps.ZONE_BROKEN_ISLES_BROKEN_SHORE, Maps.TYPE_DUNGEON, "Tomb of Sargeras - The Twisting Nether", {})


-- Highmountain
addLocation(651, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Bitestone Enclave", {})
addLocation(652, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Thunder Totem", {})
addLocation(653, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Cave of the Blood Trial", {})
addLocation(654, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Mucksnout Den", {})
addLocation(655, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Lifespring Cavern - Lifespring Lower Cavern", {})
addLocation(656, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Lifespring Cavern - Lifespring Upper Cavern", {})
addLocation(657, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Path of Huln - Floor 1", {})
addLocation(658, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Path of Huln - Floor 2", {})
addLocation(659, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Stonedark Grotto", {})
addLocation(660, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_MICRO, "Feltotem Caverns", {})

addLocation(826, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_DUNGEON, "Cave of the Bloodtotem", {})

addLocation(869, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_DUNGEON, "Highmountain - Floor 1", {})
addLocation(870, Maps.ZONE_BROKEN_ISLES_HIGHMOUNTAIN, Maps.TYPE_DUNGEON, "Highmountain - Floor 2", {})


-- Suramar
addLocation(681, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "The Arcway Vaults", {})
addLocation(682, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Felsoul Hold", {})
addLocation(683, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "The Arcway Vaults", {})
addLocation(684, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Shattered Locus - Temple of Fal'adora", {})
addLocation(685, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Shattered Locus - Falanaar Tunnels", {})
addLocation(686, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Elor'shan", {})
addLocation(687, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Kel'balor", {})
addLocation(688, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Ley Station Anora", {})
addLocation(689, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Ley Station Moonfall", {})
addLocation(690, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Ley Station Aethenar", {})
addLocation(691, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Nyell's Workshop", {})
addLocation(692, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Falanaar Arcway - Falanaar Tunnels", {})
addLocation(693, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_MICRO, "Falanaar Arcway - Falanaar Tunnels", {})

addLocation(761, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "Court of Stars - Court of Stars", {})
addLocation(762, 761, Maps.TYPE_DUNGEON, "Court of Stars - The Jeweled Estate", {})
addLocation(763, 761, Maps.TYPE_DUNGEON, "Court of Stars - The Balconies", {})

addLocation(764, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - The Nightwell", {})
addLocation(765, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - Arcing Depths", {})
addLocation(766, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - The Nighthold", {})
addLocation(767, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - Shal'Dorei Terrace", {})
addLocation(768, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - Captain's Quarters", {})
addLocation(769, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - Astromancer's Rise", {})
addLocation(770, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - The Nightspire", {})
addLocation(771, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - Elisande's Quarters", {})
addLocation(772, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Nighthold - The Font of Night", {})

addLocation(749, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Arcway", {})
addLocation(798, Maps.ZONE_BROKEN_ISLES_SURAMAR, Maps.TYPE_DUNGEON, "The Arcway", {})


-- Broken Isles
addLocation(647, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_MICRO, "Acherus: The Ebon Hold - The Heart of Acherus", {})
addLocation(648, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_MICRO, "Acherus: The Ebon Hold - Hall of Command", {})

addLocation(695, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Skyhold", {})
addLocation(702, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Netherlight Temple", {})

addLocation(719, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Mardum, the Shattered Abyss - Mardum, the Shattered Abyss", {720, 721})
addLocation(720, 719, Maps.TYPE_DUNGEON, "Mardum, the Shattered Abyss - Upper Command Center", {})
addLocation(721, 719, Maps.TYPE_DUNGEON, "Mardum, the Shattered Abyss - Lower Command Center", {})

addLocation(740, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Shadowgore Citadel - Upper Citadel", {})
addLocation(741, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Shadowgore Citadel - Lower Citadel", {})

addLocation(626, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Dalaran - The Hall of Shadows", {})
addLocation(627, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Dalaran - Dalaran", {})
addLocation(723, 627, Maps.TYPE_DUNGEON, "The Violet Hold", {})
addLocation(732, 627, Maps.TYPE_DUNGEON, "Violet Hold", {})
addLocation(734, 627, Maps.TYPE_DUNGEON, "Hall of the Guardian - Hall of the Guardian", {})
addLocation(735, 627, Maps.TYPE_DUNGEON, "Hall of the Guardian - The Guardian's Library", {})
addLocation(628, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Dalaran - The Underbelly", {})
addLocation(629, Maps.CONTINENT_BROKEN_ISLES, Maps.TYPE_DUNGEON, "Dalaran - Aegwynn's Gallery", {})


