---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by warfacez.
--- DateTime: 28.10.20 0:58
---

Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND = 895
Maps.ZONE_KUL_TIRAS_DRUSTVAR = 896
Maps.ZONE_KUL_TIRAS_STORMSONG_VALLEY = 942

addLocation(Maps.CONTINENT_KUL_TIRAS, Maps.WORLD_AZEROTH, Maps.TYPE_CONTINENT, "Kul Tiras", {})


-- Zones
addLocation(Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.CONTINENT_KUL_TIRAS, Maps.TYPE_ZONE, 'Tiragarde Sound', {})
addLocation(Maps.ZONE_KUL_TIRAS_DRUSTVAR, Maps.CONTINENT_KUL_TIRAS, Maps.TYPE_ZONE, 'Drustvar', {})
addLocation(Maps.ZONE_KUL_TIRAS_STORMSONG_VALLEY, Maps.CONTINENT_KUL_TIRAS, Maps.TYPE_ZONE, "Stormsong Valley", {})


-- Orphans
addLocation(974, Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.TYPE_ORPHAN, "Tol Dagor - Tol Dagor", {})


-- Tiragarde Sound
addLocation(975, Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.TYPE_DUNGEON, "Tol Dagor - The Drain", {})
addLocation(976, Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.TYPE_DUNGEON, "Tol Dagor - The Brig", {})
addLocation(977, Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.TYPE_DUNGEON, "Tol Dagor - Detention Block", {})
addLocation(978, Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.TYPE_DUNGEON, "Tol Dagor - Officer Quarters", {})
addLocation(979, Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.TYPE_DUNGEON, "Tol Dagor - Overseer's Redoubt", {})
addLocation(980, Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.TYPE_DUNGEON, "Tol Dagor - Overseer's Summit", {})
addLocation(936, Maps.ZONE_KUL_TIRAS_TIRAGARDE_SOUND, Maps.TYPE_DUNGEON, "Freehold", {})
