---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by warfacez.
--- DateTime: 25.10.20 13:08
---

Maps.ZONE_PANDARIA_THE_JADE_FOREST = 371
Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS = 376
Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT = 379
Maps.ZONE_PANDARIA_TOWNLONG_STEPPES = 388
Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS = 390
Maps.ZONE_PANDARIA_KRASARAG_WILDS = 418
Maps.ZONE_PANDARIA_DREAD_WASTES = 422
Maps.ZONE_PANDARIA_THE_VEILED_STAIR = 433
Maps.ZONE_PANDARIA_ISLE_OF_THUNDER = 504
Maps.ZONE_PANDARIA_ISLE_OF_GIANTS = 507
Maps.ZONE_PANDARIA_TIMELESS_ISLE = 554

addLocation(Maps.CONTINENT_PANDARIA, Maps.WORLD_AZEROTH, Maps.TYPE_CONTINENT, "Pandaria", {})

-- Zones
addLocation(Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "The Jade Forest", {})
addLocation(Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Valley of the Four Winds", {})
addLocation(Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Kun-Lai Summit", {})
addLocation(Maps.ZONE_PANDARIA_TOWNLONG_STEPPES, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Townlong Steppes", {})
addLocation(Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Vale of Eternal Blossoms", {})
addLocation(Maps.ZONE_PANDARIA_KRASARAG_WILDS, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Krasarang Wilds", {})
addLocation(Maps.ZONE_PANDARIA_DREAD_WASTES, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Dread Wastes", {})
addLocation(Maps.ZONE_PANDARIA_THE_VEILED_STAIR, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "The Veiled Stair", {})
addLocation(Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Isle of Thunder", {})
addLocation(Maps.ZONE_PANDARIA_ISLE_OF_GIANTS, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Isle of Giants", {})
addLocation(Maps.ZONE_PANDARIA_TIMELESS_ISLE, Maps.CONTINENT_PANDARIA, Maps.TYPE_ZONE, "Timeless Isle", {})


-- Orphans
addLocation(571, Maps.ZONE_PANDARIA_TIMELESS_ISLE, Maps.TYPE_ORPHAN, "Celestial Tournament", {})
addLocation(516, Maps.CONTINENT_PANDARIA, Maps.TYPE_ORPHAN, "Isle of Thunder", {})
addLocation(517, 516, Maps.TYPE_MICRO, "Lightning Vein Mine", {})

addLocation(378, Maps.WORLD_AZEROTH, Maps.TYPE_ORPHAN, "The Wandering Isle", {})
addLocation(519, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_ORPHAN, "Deepwind Gorge", {})
addLocation(520, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_ORPHAN, "Vale of Eternal Blossoms", {})
addLocation(498, Maps.ZONE_PANDARIA_KRASARAG_WILDS, Maps.TYPE_ORPHAN, "Krasarang Wilds", {})
addLocation(488, Maps.ZONE_PANDARIA_THE_VEILED_STAIR, Maps.TYPE_ORPHAN, "Dagger in the Dark", {})
addLocation(447, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_ORPHAN, "A Brewing Storm", {})
addLocation(448, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_ORPHAN, "The Jade Forest", {})
addLocation(417, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_ORPHAN, "Temple of Kotmogu", {})
addLocation(452, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_ORPHAN, "Brewmoon Festival", {})
addLocation(449, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_ORPHAN, "Temple of Kotmogu", {})
addLocation(417, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_ORPHAN, "Temple of Kotmogu", {})
addLocation(450, Maps.ZONE_PANDARIA_KRASARAG_WILDS, Maps.TYPE_ORPHAN, "Unga Ingoo", {})
addLocation(451, Maps.ZONE_PANDARIA_DREAD_WASTES, Maps.TYPE_ORPHAN, "Assault on Zan'vess", {})
addLocation(456, Maps.ZONE_PANDARIA_THE_VEILED_STAIR, Maps.TYPE_ORPHAN, "Terrace of Endless Spring", {})
addLocation(486, Maps.ZONE_PANDARIA_KRASARAG_WILDS, Maps.TYPE_ORPHAN, "Krasarang Wilds - Krasarang Wilds", {})
addLocation(487, Maps.ZONE_PANDARIA_KRASARAG_WILDS, Maps.TYPE_ORPHAN, "A Little Patience - Krasarang Wilds", {})
addLocation(843, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_ORPHAN, "Shado-Pan Showdown", {})
addLocation(728, Maps.ZONE_PANDARIA_THE_VEILED_STAIR, Maps.TYPE_ORPHAN, "Terrace of Endless Springr", {})


-- The Veiled Stair


-- Dread Wastes
addLocation(474, Maps.ZONE_PANDARIA_DREAD_WASTES, Maps.TYPE_DUNGEON, "Heart of Fear - Oratorium of the Voice", {})
addLocation(475, Maps.ZONE_PANDARIA_DREAD_WASTES, Maps.TYPE_DUNGEON, "Heart of Fear - Heart of Fear", {})


-- Jade Forest
addLocation(372, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_MICRO, "Greenstone Quarry - Upper Quarry", {})
addLocation(373, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_MICRO, "Greenstone Quarry - Lower Quarry", {})
addLocation(374, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_MICRO, "The Widow's Wail", {})
addLocation(375, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_MICRO, "Oona Kagu", {})
addLocation(429, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_DUNGEON, "Temple of the Jade Serpent - Temple of the Jade Serpent", {})
addLocation(430, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_DUNGEON, "Temple of the Jade Serpent - The Scrollkeeper's Sanctum", {})
addLocation(791, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_DUNGEON, "Temple of the Jade Serpent - Temple of the Jade Serpent", {})
addLocation(792, Maps.ZONE_PANDARIA_THE_JADE_FOREST, Maps.TYPE_DUNGEON, "Temple of the Jade Serpent - The Scrollkeeper's Sanctum", {})


-- Valley of the Four Winds
addLocation(377, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_MICRO, "Cavern of Endless Echoes", {})
addLocation(439, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_DUNGEON, "Stormstout Brewery - Grain Cellar", {})
addLocation(440, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_DUNGEON, "Stormstout Brewery - Stormstout Brewhall", {})
addLocation(441, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_DUNGEON, "Stormstout Brewery - The Great Wheel", {})
addLocation(442, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_DUNGEON, "Stormstout Brewery - The Tasting Room", {})
addLocation(872, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_DUNGEON, "Stormstout Brewery - Stormstout Brewery", {})
addLocation(873, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_DUNGEON, "Stormstout Brewery - Floor 1", {})
addLocation(874, Maps.ZONE_PANDARIA_VALLEY_OF_THE_FOUR_WINDS, Maps.TYPE_DUNGEON, "Stormstout Brewery - Floor 2", {})

-- Townlong Steppes
addLocation(389, Maps.ZONE_PANDARIA_TOWNLONG_STEPPES, Maps.TYPE_MICRO, "Niuzao Temple", {})


-- Kun-Lai Summit
addLocation(380, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "Howlingwind Cavern", {})
addLocation(381, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "Pranksters' Hollow", {})
addLocation(382, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "Knucklethump Hole ", {})
addLocation(383, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "The Deeper - Upper Deep", {})
addLocation(384, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "The Deeper - Lower Deep", {})
addLocation(385, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "Tomb of Conquerors", {})
addLocation(386, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "Ruins of Korune - Ruins of Korune", {})
addLocation(387, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "Ruins of Korune - Crypt of Korune", {})
addLocation(434, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_MICRO, "The Ancient Passage", {})
addLocation(443, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_DUNGEON, "Shado-Pan Monastery - Shado-Pan Monastery", {})
addLocation(444, 443, Maps.TYPE_DUNGEON, "Shado-Pan Monastery - Cloudstrike Dojo", {})
addLocation(445, 443, Maps.TYPE_DUNGEON, "Shado-Pan Monastery - Snowdrift Dojo", {})
addLocation(446, 443, Maps.TYPE_DUNGEON, "Shado-Pan Monastery - Sealed Chambers", {})
addLocation(480, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_DUNGEON, "Proving Grounds", {})
addLocation(481, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_DUNGEON, "Crypt of Forgotten Kings - Upper Burial Chamber", {})
addLocation(482, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_DUNGEON, "Crypt of Forgotten Kings - Crypt Depths", {})
addLocation(489, Maps.ZONE_PANDARIA_KUN_LAI_SUMMIT, Maps.TYPE_DUNGEON, "Dagger in the Dark", {})


-- Townlong Steppes
addLocation(457, Maps.ZONE_PANDARIA_TOWNLONG_STEPPES, Maps.TYPE_DUNGEON, "Siege of Niuzao Temple - Siege of Niuzao Temple", {})
addLocation(458, 457, Maps.TYPE_DUNGEON, "Siege of Niuzao Temple - The Hollowed Out Tree ", {})
addLocation(459, 457, Maps.TYPE_DUNGEON, "Siege of Niuzao Temple - Upper Tree Ring", {})


-- Vale of Eternal Blossoms
addLocation(391, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_MICRO, "Shrine of Two Moons - Hall of the Crescent Moon", {})
addLocation(392, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_MICRO, "Shrine of Two Moons - The Imperial Mercantile", {})
addLocation(393, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_MICRO, "Shrine of Seven Stars - The Emperor's Step", {})
addLocation(394, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_MICRO, "Shrine of Seven Stars - The Imperial Exchange", {})
addLocation(395, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_MICRO, "Guo-Lai Halls - Guo-Lai Halls", {})
addLocation(396, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_MICRO, "Guo-Lai Halls - The Hall of the Serpent", {})
addLocation(556, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Siege of Orgrimmar", {557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570})
addLocation(557, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Pools of Power", {})
addLocation(558, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Vault of Y'Shaarj", {})
addLocation(559, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Gates of Orgrimmar", {})
addLocation(560, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - The Valley of Strength", {})
addLocation(561, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - The Cleft of Shadow", {})
addLocation(562, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - The Descent", {})
addLocation(563, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Kor'Kron Barracks", {})
addLocation(564, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - The Menagerie", {})
addLocation(565, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - The Siegeworks", {})
addLocation(566, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Chamber of the Paragons", {})
addLocation(567, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - The Inner Sanctum", {})
addLocation(568, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Terrace of Endless Spring", {})
addLocation(569, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Temple of the Jade Serpent", {})
addLocation(570, 556, Maps.TYPE_DUNGEON, "Siege of Orgrimmar - Temple of the Red Crane", {})

addLocation(521, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Vale of Eternal Blossoms", {})
addLocation(471, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Mogu'shan Vaults - Dais of Conquerors", {})
addLocation(472, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Mogu'shan Vaults - The Repository", {})
addLocation(473, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Mogu'shan Vaults - Forge of the Endless", {})

addLocation(437, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Gate of the Setting Sun - Gate of the Setting Sun", {})
addLocation(438, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Gate of the Setting Sun - Gate Watch Tower", {})
addLocation(453, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Mogu'shan Palace - The Crimson Assembly Hall", {})
addLocation(454, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Mogu'shan Palace - Vaults of Kings Past", {})
addLocation(455, Maps.ZONE_PANDARIA_VALE_OF_ETERNAL_BLOSSOMS, Maps.TYPE_DUNGEON, "Mogu'shan Palace - Throne of Ancient Conquerors", {})


-- Timeless Isle
addLocation(555, Maps.ZONE_PANDARIA_TIMELESS_ISLE, Maps.TYPE_MICRO, "Cavern of Lost Spirits", {})
addLocation(505, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_MICRO, "Lightning Vein Mine", {})
addLocation(506, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_MICRO, "The Swollen Vault", {})

addLocation(508, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Throne of Thunder - Overgrown Statuary", {})
addLocation(509, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Throne of Thunder - Royal Amphitheater", {})
addLocation(510, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Throne of Thunder - Forgotten Depths", {})
addLocation(511, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Throne of Thunder - Roost of Ji-Kun", {})
addLocation(512, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Throne of Thunder - Halls of Flesh-Shaping", {})
addLocation(513, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Throne of Thunder - Hall of Kings", {})
addLocation(514, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Throne of Thunder - Pinnacle of Storms", {})
addLocation(515, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Throne of Thunder - Hidden Cell", {})
addLocation(518, Maps.ZONE_PANDARIA_ISLE_OF_THUNDER, Maps.TYPE_DUNGEON, "Thunder King's Citadel", {})


-- Krasarang Wilds
addLocation(419, Maps.ZONE_PANDARIA_KRASARAG_WILDS, Maps.TYPE_MICRO, "Ruins of Ogudei - Alliance Excavation", {})
addLocation(420, Maps.ZONE_PANDARIA_KRASARAG_WILDS, Maps.TYPE_MICRO, "Ruins of Ogudei - Ruins of Ogudei", {})
addLocation(421, Maps.ZONE_PANDARIA_KRASARAG_WILDS, Maps.TYPE_MICRO, "Ruins of Ogudei - Reliquary Incursion", {})
