---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by warfacez.
--- DateTime: 28.10.20 0:58
---

Maps.ZONE_ZANDALAR_ZULDAZAR = 862
Maps.ZONE_ZANDALAR_NAZMIR = 863
Maps.ZONE_ZANDALAR_VOLDUN = 864

addLocation(Maps.CONTINENT_ZANDALAR, Maps.WORLD_AZEROTH, Maps.TYPE_CONTINENT, "Zandalar", {})

-- Zones
addLocation(Maps.ZONE_ZANDALAR_ZULDAZAR, Maps.CONTINENT_ZANDALAR, Maps.TYPE_ZONE, "Zuldazar", {})
addLocation(Maps.ZONE_ZANDALAR_NAZMIR, Maps.CONTINENT_ZANDALAR, Maps.TYPE_ZONE, "Nazmir", {})
addLocation(Maps.ZONE_ZANDALAR_VOLDUN, Maps.CONTINENT_ZANDALAR, Maps.TYPE_ZONE, "Vol'dun", {})


-- Zuldazar
addLocation(934, Maps.ZONE_ZANDALAR_ZULDAZAR, Maps.TYPE_DUNGEON, "Atal'Dazar - Atal'Dazar", {})
addLocation(935, Maps.ZONE_ZANDALAR_ZULDAZAR, Maps.TYPE_DUNGEON, "Atal'Dazar - Sacrificial Pits", {})