---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by warfacez.
--- DateTime: 28.10.20 2:49
---

SLASH_MAPSCHECK1 = '/mapscheck'
SLASH_MAPSCHECKALL1 = '/mapscheckall'


local function MapsCheckHandler(uiMapId)

    local function debugObject(objectData, stringData)
        for index, data in ipairs(objectData) do
            if type(data) == "table" or type(data) == 'array' then
                stringData = stringData .. debugObject(data)
            end
            stringData = stringData .. tostring(data)
            return stringData
        end
    end

    local i = Maps:getMapByUiMapId(uiMapId)
    local info = C_Map.GetMapInfo(uiMapId)

    print("DB Data/WoW Data:\n" ..
        "uiMapId: " .. i.uiMapId .. "/" .. info.mapID .. "\n" ..
        "mapFile: " .. i.mapFile .. "/" .. info.name .. "\n" ..
        "type: " .. i.type.id .. "/" .. info.mapType .. "\n" ..
        "parentUiMapId: " .. i.parentUiMapId .. "/" .. info.parentMapID .. "\n" ..
        "flags:  /" .. info.flags .. "\n" ..
        ""
    )

end


local function MapsCheckAllHandler()
    local errors = 0
    local locations = Maps:getAllLocations()
    local amountLocations = table.getn(locations)
    for index, data in ipairs(locations) do
        if (data.uiMapId == nil) then
            print("W: uiMapId nil: " .. data.parentUiMapId)
        end
        wowData = C_Map.GetMapInfo(data.uiMapId)
        if (data.type == false) then
            errors = errors + 1
            print("W: Type wrong: " .. data.uiMapId)
        elseif data.parentUiMapId == nil then
            print("W: parentUiMapId nil: " .. data.uiMapId)
        else
            if (data.type.id ~= wowData.mapType or data.parentUiMapId ~= wowData.parentMapID) then
                errors = errors + 1
                print(data.uiMapId .. ": Type: " .. data.type.id .. "/" .. wowData.mapType .. ", Parent:" .. data.parentUiMapId .. "/" .. wowData.parentMapID)
            end

            if (data.mapFile ~= wowData.name) then
                --print(data.uiMapId .. ": " .. data.mapFile .. "/" .. wowData.name)
            end
        end
    end
    print("Check Finished! There was  " .. amountLocations .. " records and " .. errors .. " errors.")
end

SlashCmdList["MAPSCHECK"] = MapsCheckHandler
SlashCmdList["MAPSCHECKALL"] = MapsCheckAllHandler