name: CI - Changelog

on:
  push:
    branches: [ master ]

jobs:
  changelog_prerelease:
    name: Update Changelog For Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.WIKI_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
          addSections: '{"added":{"prefix":"###Added","labels":["added","Added"]},"changed":{"prefix":"###Changed","labels":["changed","Changed"]},"fixed":{"prefix":"###Fixed","labels":["fixed","Fixed"]},"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
      - name: Fix headers in changelog
        run: |
          sed -Ei "s/###(.+)/### \1/" CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for PR
          file_pattern: CHANGELOG.md
