# This is a basic workflow to help you get started with Actions

name: Create Release Branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  createrelease:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
#          persist-credentials: false

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Update changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        id: Changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for PR
          file_pattern: CHANGELOG.md
#      - name: Push changelog
#        run: |
#          git add CHANGELOG.md
#          git commit -m "Update Changelog for ${{ env.RELEASE_VERSION }}"
#          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" release/${{ env.RELEASE_VERSION }}
#          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Extract release notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: ${{ steps.Changelog.outputs.changelog }}
#          body: ${{ steps.extract_release_notes.outputs.release_notes }}
          draft: false
          prerelease: ${{ contains('-alpha', env.RELEASE_VERSION) || contains('-beta', env.RELEASE_VERSION) }}
      - name: Create release branch
        run: |
          git checkout -b release/${{ env.RELEASE_VERSION }}
          git push origin release/${{ env.RELEASE_VERSION }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Create pull request into master
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ env.RELEASE_VERSION }}
          base: master
          title: ${{ env.RELEASE_VERSION }} into master
          reviewers: ${{ github.event.issue.user.login }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: release
          commit-message: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version.

      - name: Create pull request into develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ env.RELEASE_VERSION }}
          base: develop
          title: ${{ env.RELEASE_VERSION }} into develop
          reviewers: ${{ github.event.issue.user.login }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: release
          commit-message: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version.