name: Create Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
  push:
    tags:
      - 'v*'

jobs:
  update_package:
    name: Update package version in .toc
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Get version from tag
        env:
          GITHUB_REF: $
        run: echo "CURRENT_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Update .toc
        run: |
          sed -i "s/## Version: .*/## Version: ${{ env.CURRENT_VERSION }}/" Maps.toc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update version in toc for tag ${{ env.CURRENT_VERSION }}
          file_pattern: Maps.toc

  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    needs: update_package
    steps:
      - name: Get version from tag
        env:
          GITHUB_REF: $
        run: echo "CURRENT_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.WIKI_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          breakingLabel: '## Changed'
          breakingLabels: 'backwards-incompatible,breaking,changed,Changed'
          enhancementLabel: '## Added'
          enhancementLabels: 'enhancement,Enhancement,added,Added'
          bugsLabel: '## Fixed'
          bugLabels: 'bug,Bug,fixed,Fixed'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for tag ${{ env.CURRENT_VERSION }}
          file_pattern: CHANGELOG.md

  release_notes:
    name: Create Release Notes
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Get version from tag
        env:
          GITHUB_REF: $
        run: echo "CURRENT_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Extract release notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1
#      - name: Get Changelog Entry
#        id: changelog_reader
#        uses: mindsers/changelog-reader-action@v1
#        with:
#          version: ${{ env.CURRENT_VERSION }}
#          path: ./CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_VERSION }}
          release_name: Release ${{ env.CURRENT_VERSION }}
#          body: ${{ steps.changelog_reader.outputs.changes }}
          body: ${{ steps.extract_release_notes.outputs.release_notes }}
          draft: false
          prerelease: ${{ contains('beta', env.CURRENT_VERSION) || contains('alpha', env.CURRENT_VERSION) }}