on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  issues:
    types: [opened, edited, closed, reopened, assigned, milestoned]
  issue_comment:
    types: [created, edited, deleted]


name: Discord Notification

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: binotaliu/action-discord-notifier@v1
        with:
          message-title: WoWMua Maps update
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
